name: Attributioner
main: au.com.addstar.attributioner.Attributioner
version: 1.0
api-version: '1.21'
softdepend: [WorldGuard]
commands:
  attributioner:
    description: Admin commands for Attributioner
    permission: attributioner.reload
    usage: /attributioner <reload|regions|debug|info>
